### ISSUE TITLE
reproduce result on REDD

### ISSUE THREAD

**Issue by Hessen525** [MingjunZhong/transferNILM#1] opened 2020-03-15 18:14 UTC
Hi, Dr.Zhong @MingjunZhong 
Thanks for sharing the code. I follow the instructions and run this project successfully. Keep the same parameter as you submit. But the results I get for REDD are quite different from your reported results. I'm wondering if I missed anything? I RUN 50 epochs. 
for train, I run 
python3 seq2point_train.py --appliance_name fridge --datadir ./dataset_management/redd/ --save_dir ./trained_model --transfer_model False --crop_dataset None
for test, I run 
python3 seq2point_test.py --appliance_name fridge --datadir ./dataset_management/redd/ --trained_model_dir ./trained_model --save_results_dir ./result --transfer False --crop_dataset None --plot_results True

Fridge, I got same SAE value, but the MAE is big different(35.2376 vs 28.104). 

![fridge-all](https://user-images.githubusercontent.com/25447481/76707632-cdaad100-672b-11ea-9044-49c8a5446509.png)

Any other application will be test soon. 
Any reply/help will be much appreciated!

**Comment by MingjunZhong** [comment] 2020-03-16 11:11
@Hessen525 When training, are you using early-stopping as I see it ran 50 iterations? I can't see the reasons why it has so much difference. What about other appliances?

**Comment by Hessen525** [comment] 2020-03-16 13:38
![washingmachine](https://user-images.githubusercontent.com/25447481/76762266-ed91d180-67cb-11ea-87f5-5703bb41a72a.png)
![microwave](https://user-images.githubusercontent.com/25447481/76762833-ff27a900-67cc-11ea-8c69-4584558022b4.png)

**Comment by Hessen525** [comment] 2020-03-17 02:55
![fridge-all](https://user-images.githubusercontent.com/25447481/76764617-1b791500-67d0-11ea-99d1-6e3ec21156df.png)

![dishwasher](https://user-images.githubusercontent.com/25447481/76817233-43eb2880-683d-11ea-8797-baaaaa3ed10b.png)

@MingjunZhong Sorry for disturbing you again, Dr. Zhong.
I try in my mac and windows, for REDD dataset, get same results. the others applications result graph look very well, but the plot graph of washingmachine looks abnormal because the ground truth value of it is keep zero all the time.

**Comment by Hessen525** [comment] 2020-03-17 03:00
above graph trained and tested for all data in REDD for specified application, but the following is trained all data and test first 10000 data point.  the results look very well. 
<img width="640" alt="21148EA5BE1A3E183BE9E49B03187A10" src="https://user-images.githubusercontent.com/25447481/76817649-6d588400-683e-11ea-81ba-9f6fa24b4a46.png">

<img width="640" alt="7B76761C3A856C1B0969BC5A328013F8" src="https://user-images.githubusercontent.com/25447481/76817809-d7712900-683e-11ea-9b8e-da1950770a02.png">

**Comment by Hessen525** [comment] 2020-03-17 09:29
@MingjunZhong Hi, Dr.Zhong.
Thanks for your help again. Your project is very good! 
I have found the problem, I guess the parameter set wrong or your dataset is different with that downloaded from http://redd.csail.mit.edu/data/low_freq.tar.bz2. 
In redd_parameters.py file, you set as following:
    'washingmachine': {
        'windowlength': 599,
        'on_power_threshold': 20,
        'max_on_power': 3999,
        'mean': 400,
        'std': 700,
        's2s_length': 2000,
        'houses': [1, 2, 3],
        'channels': [19, 7, 13],
        'train_build': [2, 3],
        'test_build': 1

For washingmachine, you set building 1 as test_dataset where channels_19 as washingmachine data, but I look at that file, it is all zero, so that could be interpreted why ground truth is keep zero in results plot graph.

**Comment by Hessen525** [comment] 2020-03-17 09:53
![washingmachine-f](https://user-images.githubusercontent.com/25447481/76844213-ecb67980-6877-11ea-86c7-456041fa887f.png)
I change Channel_19 TO  20, It works very well, Is that used in your experiment, Dr.Zhong?

**Comment by MingjunZhong** [comment] 2020-03-17 10:39
@Hessen525 So now it looks correct for washing machine and as well as other appliances. Thank you for the post, the problems was then the labelling.

**Comment by MingjunZhong** [comment] 2020-03-17 14:28
@Hessen525 I think we can close this issue now.

**Closed as completed by MingjunZhong** 2020-03-17 14:28 UTC

**Comment by Hessen525** [comment] 2020-03-17 18:53
Sure, Thanks!

**Comment by Engr-KhurramIqbal** [comment] 2020-05-15 06:22
@Hessen525 will you please explain how to set up the virtual environment on windows.Actually I am unable to create environment by using yml file due to difference in  Operating system.I am windows os user.Will you please share the yml files for windows os.thanks

**Comment by Hessen525** [comment] 2020-05-17 07:54
Hi, @khurramch 
Do not worry about the environment required . All you need is to run the program in Pycharm and install what is missing. In fact, there are not many libraries to install!

**Comment by Engr-KhurramIqbal** [comment] 2020-05-17 08:30
hello,@Hessen525 
Thanks for your reply.

**Comment by hellowangqian** [comment] 2020-05-29 11:19
Hi @Hessen525 
Are you able to reproduce similar results to those reported in the paper on REDD dataset? Thanks. Here is what I can get: https://github.com/MingjunZhong/NeuralNetNilm/issues/3#issue-554857599

**Comment by Hessen525** [comment] 2020-05-31 13:23
Hi @hellowangqian 
Do not worry about that. If you want to compare with this algorithm, you have two choices:
 1. Compare your model with the results in this article, in the same case as  their paper.
 2.  Try to compare results in other data sets.

Both is better.
